In [1]:
import numpy

### Q1

In [4]:
a = numpy.random.normal(size=25)
print(a)

[ 0.30608712  1.08353754 -1.11062772  0.52715576  1.11289404 -0.03865803
  0.77330322 -0.20497516 -0.23898831  0.04677129 -0.4404054  -0.34183496
  0.42237132  0.09183366  0.59506677  0.48560927  1.59078079 -0.240504
  0.47873255  2.23353055  1.45965388 -0.15752744  0.34995513 -0.72440723
  0.32747438]


### Q2.

In [6]:
a = numpy.random.rand(30)
b = a.mean()
print(b)

0.531492081934436


### Q3.

In [9]:
a = numpy.arange(1, 101)
b = a.reshape(10, 10)
print(b)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


### Q4

In [11]:
a = numpy.random.rand(10, 10)
min = a.min()
max = a.max()
print(min)
print(max)

0.0019954047275496656
0.9967789978738961


### Q5

In [16]:
f = numpy.array([1,2])
g = numpy.array([4,5])
a = numpy.dot(f, g)
print(a)

14


### Q6

In [17]:
x=numpy.array([[1,2],[3,4]])
y=numpy.array([[5,6]])
a = numpy.concatenate((x, y), axis=0)
print(a)

[[1 2]
 [3 4]
 [5 6]]


### Q7.

In [18]:
a = numpy.array([1,2,3,2,3,4,3,4,5,6])
b = numpy.array([7,2,10,2,7,4,9,4,9,8])
c = numpy.intersect1d(a, b)
print(c)

[2 4]


### Q8.

In [19]:
arr = numpy.array([10,5,8,4,7,2,3,1])
a = numpy.sort(arr)
print(a)

[ 1  2  3  4  5  7  8 10]
